title: Hello, world! Myself Shrivibhavan
description: > # this means to ignore newlines until "baseurl:"
 Hii, Namaskar🙏, myself Shrivibhavan. I'm studying in First Year of Computer Science and Engineering at KIT Kolhapur.
  On this page I will share you generally latest Global News, Technology, etc.📌 
permalink: ':title/'
baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
username_twitter: shreevibhavan

# Author Settings
author: David Freeman # add your name
author-img: david-freeman.jpg # add your photo
about-author: I am a web developer focusing on front-end development. Always hungry to keep learning. # add description
social-twitter: shreevibhavan
social-facebook: shreevibhavan
social-github: shrivibhavan
social-linkedin: shreevibhavan
social-email: shrivibhavan.deshpande@gmail.com

# Disqus
#discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
