# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Shrivibhavan Deshpande
title: Personal Blog 
email: shrivibhavan.deshpande@gmail.com

# Social links
twitter_username: shreevibhavan
github_username:  shrivibhavan
# dribbble_username: jekyll
facebook_username: shreevibhavan
# flickr_username: jekyll
instagram_username: shreevibhavan
# pinterest_username: jekyll
youtube_username: UCaM7zGlwDvH2gQWqmw1hewg
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: Profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hii, Namaskar🙏, myself Shrivibhavan. I'm studying in First Year of Computer Science and Engineering at KIT Kolhapur.
  On this page I will share you generally latest Global News, Technology, etc.📌
  
projects_title: 1) Lokshikshan We will do this project to teach the people who are un-experienced to the latest Tech. and how it helps us to make our life easier
 
# Experience Section
# experience_title: Experience

 #Education Section
 #educaton_title: Education- 12th Standar Graduated from New Collge Kolhapur

# More Section
more_title: A Little More About Me 🙂
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests is in software engineering  some of my other interests and hobbies are:
   - Trekking
   - Coding
   - Cycling
   - Riding Motorcycle
   - Exploring world of New Technology
   
# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
/*!
 * Dark Mode Switch v1.0.1 (https://github.com/coliff/dark-mode-switch)
 * Copyright 2021 C.Oliff
 * Licensed under MIT (https://github.com/coliff/dark-mode-switch/blob/main/LICENSE)
 */

var darkSwitch = document.getElementById("darkSwitch");
window.addEventListener("load", function () {
  if (darkSwitch) {
    initTheme();
    darkSwitch.addEventListener("change", function () {
      resetTheme();
    });
  }
});

/**
 * Summary: function that adds or removes the attribute 'data-theme' depending if
 * the switch is 'on' or 'off'.
 *
 * Description: initTheme is a function that uses localStorage from JavaScript DOM,
 * to store the value of the HTML switch. If the switch was already switched to
 * 'on' it will set an HTML attribute to the body named: 'data-theme' to a 'dark'
 * value. If it is the first time opening the page, or if the switch was off the
 * 'data-theme' attribute will not be set.
 * @return {void}
 */
function initTheme() {
  var darkThemeSelected =
    localStorage.getItem("darkSwitch") !== null &&
    localStorage.getItem("darkSwitch") === "dark";
  darkSwitch.checked = darkThemeSelected;
  darkThemeSelected
    ? document.body.setAttribute("data-theme", "dark")
    : document.body.removeAttribute("data-theme");
}

/**
 * Summary: resetTheme checks if the switch is 'on' or 'off' and if it is toggled
 * on it will set the HTML attribute 'data-theme' to dark so the dark-theme CSS is
 * applied.
 * @return {void}
 */
function resetTheme() {
  if (darkSwitch.checked) {
    document.body.setAttribute("data-theme", "dark");
    localStorage.setItem("darkSwitch", "dark");
  } else {
    document.body.removeAttribute("data-theme");
    localStorage.removeItem("darkSwitch");
  }
}
