# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Shrivibhavan Deshpande
title: Personal Blog and News
email: shrivibhavan.deshpande@gmail.com

# Social links
twitter_username: shreevibhavan
github_username:  shrivibhavan
# dribbble_username: jekyll
facebook_username: shreevibhavan
# flickr_username: jekyll
instagram_username: shreevibhavan
# pinterest_username: jekyll
youtube_username: UCaM7zGlwDvH2gQWqmw1hewg
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: Profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hii, Namaskar🙏, myself Shrivibhavan. I'm studying in First Year of Computer Science and Engineering at KIT Kolhapur.
  On this page I will share you generally latest Global News, Technology, etc.📌
  
projects_title: 1) Lokshikshan We will do this project to teach the people who are un-experienced to the latest Tech. and how it helps us to make our life easier
 
# Experience Section
# experience_title: Experience

 #Education Section
 #educaton_title: Education- 12th Standar Graduated from New Collge Kolhapur

# More Section
more_title: A Little More About Me 🙂
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests is in software engineering  some of my other interests and hobbies are:
   - Trekking
   - Coding
   - Cycling
   - Riding Motorcycle
   - Exploring world of New Technology
   
# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

dark_mode:
    always:            false
    dynamic:           true
    sunrise:           6
    sunset:            18
    icon:              true

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
